name: harvestflow
description: "SoulWinning is an empowering offline-first mobile app designed to streamline evangelism efforts, offering seamless member management, automated SMS communication, and intelligent follow-up reminders, all stored securely on your device."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  sqflite: ^2.0.0
  path: ^1.8.3
#  sqflite_common_web: ^1.0.3
  sqflite_common_ffi: ^2.3.0
  riverpod: ^2.0.0
  flutter_riverpod: ^2.0.0
  http: ^1.0.0
  flutter_local_notifications: ^19.0.0
  contacts_service: 0.6.3
  intl: 0.20.2
  permission_handler: ^12.0.0
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
